# Generated by Django 4.2.5 on 2023-09-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_armor_product_type_remove_product_bow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sword',
        ),
    ]
